export const seedLocation = {
  id: "loc-1",
  name: "Parkir Mall XYZ",
  slug: "mall-xyz",
  address: "Jl. Sudirman No. 1, Jakarta",
  latitude: -6.2088,
  longitude: 106.8456,
  description: "Parking at Mall XYZ",
  pricingMode: "FLAT_HOURLY" as const,
  balance: 500000,
  isActive: true,
  createdAt: new Date("2026-01-01"),
  updatedAt: new Date("2026-01-01"),
};

export const seedLocationFixedDaily = {
  id: "loc-2",
  name: "Gedung Parkir ABC",
  slug: "gedung-abc",
  address: "Jl. Gatot Subroto No. 5, Jakarta",
  latitude: -6.2245,
  longitude: 106.8102,
  description: "Daily parking at Gedung ABC",
  pricingMode: "FIXED_DAILY" as const,
  balance: 0,
  isActive: true,
  createdAt: new Date("2026-01-01"),
  updatedAt: new Date("2026-01-01"),
};

export const seedPricingTiers = [
  {
    id: "tier-1",
    locationId: "loc-1",
    vehicleType: "MOTORCYCLE" as const,
    firstHourRate: 3000,
    additionalHourRate: 2000,
    dailyRate: 25000,
    maxDailyRate: 25000,
    gracePeriodMinutes: 15,
    isActive: true,
  },
  {
    id: "tier-2",
    locationId: "loc-1",
    vehicleType: "CAR" as const,
    firstHourRate: 10000,
    additionalHourRate: 5000,
    dailyRate: 75000,
    maxDailyRate: 75000,
    gracePeriodMinutes: 15,
    isActive: true,
  },
  {
    id: "tier-3",
    locationId: "loc-1",
    vehicleType: "BUS" as const,
    firstHourRate: 20000,
    additionalHourRate: 10000,
    dailyRate: 150000,
    maxDailyRate: 150000,
    gracePeriodMinutes: 15,
    isActive: true,
  },
  {
    id: "tier-4",
    locationId: "loc-2",
    vehicleType: "MOTORCYCLE" as const,
    firstHourRate: 5000,
    additionalHourRate: 5000,
    dailyRate: 15000,
    maxDailyRate: 15000,
    gracePeriodMinutes: 0,
    isActive: true,
  },
  {
    id: "tier-5",
    locationId: "loc-2",
    vehicleType: "CAR" as const,
    firstHourRate: 20000,
    additionalHourRate: 20000,
    dailyRate: 50000,
    maxDailyRate: 50000,
    gracePeriodMinutes: 0,
    isActive: true,
  },
];

export const seedVehicleRules = [
  {
    id: "rule-1",
    locationId: "loc-1",
    vehicleType: "MOTORCYCLE" as const,
    name: "Motor - plat pendek",
    pattern: "^[A-Z]{1,2}\\d{1,4}[A-Z]{0,2}$",
    priority: 10,
    isActive: true,
  },
  {
    id: "rule-2",
    locationId: "loc-1",
    vehicleType: "CAR" as const,
    name: "Mobil - plat 3 huruf belakang",
    pattern: "^[A-Z]{1,2}\\d{1,4}[A-Z]{3}$",
    priority: 20,
    isActive: true,
  },
  {
    id: "rule-3",
    locationId: "loc-1",
    vehicleType: "BUS" as const,
    name: "Bus/Truck - format khusus",
    pattern: "^B\\s?\\d{3,4}\\s?[A-Z]{2,3}$",
    priority: 30,
    isActive: true,
  },
];

export const seedTicket = {
  id: "ticket-1",
  locationId: "loc-1",
  userId: null,
  licensePlate: "B1234ABC",
  licensePlateRaw: "B 1234 ABC",
  vehicleType: "CAR" as const,
  durationMinutes: 120,
  totalPrice: 15000,
  status: "PENDING" as const,
  approvalCode: null,
  timeoutCode: null,
  validFrom: null,
  validUntil: null,
  paidAt: null,
  createdAt: new Date("2026-04-15T10:00:00Z"),
  updatedAt: new Date("2026-04-15T10:00:00Z"),
};

export const seedPaidTicket = {
  id: "ticket-2",
  locationId: "loc-1",
  userId: "user-1",
  licensePlate: "B5678XYZ",
  licensePlateRaw: "B 5678 XYZ",
  vehicleType: "CAR" as const,
  durationMinutes: 60,
  totalPrice: 10000,
  status: "PAID" as const,
  approvalCode: "4827",
  timeoutCode: "6301",
  validFrom: new Date("2026-04-15T10:05:00Z"),
  validUntil: new Date("2026-04-15T11:05:00Z"),
  paidAt: new Date("2026-04-15T10:05:00Z"),
  createdAt: new Date("2026-04-15T10:00:00Z"),
  updatedAt: new Date("2026-04-15T10:05:00Z"),
};

export const seedPayment = {
  id: "pay-1",
  ticketId: "ticket-1",
  amount: 15000,
  qrisPayload: JSON.stringify({
    ticketId: "ticket-1",
    amount: 15000,
    merchantName: "Parkir Nyalira",
    locationName: "Parkir Mall XYZ",
  }),
  qrisExpiry: new Date("2026-04-15T10:15:00Z"),
  status: "PENDING" as const,
  webhookPayload: null,
  webhookSignature: null,
  paidAt: null,
  createdAt: new Date("2026-04-15T10:00:00Z"),
  updatedAt: new Date("2026-04-15T10:00:00Z"),
};

export const seedLocationAdmin = {
  id: "admin-1",
  userId: "admin-user-1",
  locationId: "loc-1",
  role: "OWNER" as const,
  createdAt: new Date("2026-01-01"),
};
